### ISSUE TITLE
请问支持秒级周期的K线吗，比如10s周期的K线图

### ISSUE THREAD

**Issue by chuckding25** [jones2000/HQChart#119]
如果在这个目前项目的基础上改，工作量大吗？难度如何？

Javascript刚入门不久。

**Comment by jones2000** [comment]
支持秒周期的。 看教程 [HQChart使用教程1- 如何快速创建一个K线图页面](https://blog.csdn.net/jones2000/article/details/90272733)

**Comment by jones2000** [comment]
新手如果要改这个项目，比较难， 代码量大概9W行。涉及到编译原理
