### ISSUE TITLE
有没有支持orderflow

### ISSUE THREAD

**Issue by 51bitquant** [jones2000/HQChart#127]
有支持orderflow的吗？

**Comment by jones2000** [comment]
支持订单流的
[https://opensource2.zealink.com/hqweb/demo/demo_orderflow.html](https://opensource2.zealink.com/hqweb/demo/demo_orderflow.html)
[HQChart使用教程30-K线图如何对接第3方数据32-订单流](https://jones2000.blog.csdn.net/article/details/122888661)
