### ISSUE TITLE
vue版本的如何提换成自己的数据呢

### ISSUE THREAD

**Issue by Qchuanwudi** [jones2000/HQChart#130]
vue版本的如何提换成自己的数据呢，在哪里填充自己的数据呢，没有像serves那种吗

**Comment by jones2000** [comment]
[HQChart使用教程30-K线图如何对接第3方数据1](https://blog.csdn.net/jones2000/article/details/100181279)
第3方数据对接  [https://github.com/jones2000/HQChart-Super/tree/master/hqchart_super_eastmoney_demo](https://github.com/jones2000/HQChart-Super/tree/master/hqchart_super_eastmoney_demo)
