### ISSUE TITLE
内置测试数据接口挂了

### ISSUE THREAD

**Issue by mydal** [jones2000/HQChart#139]
想问一下 内置测试数据的接口 什么时候可以恢复

**Comment by jones2000** [comment]
内置测试接口正常，如果不能访问重启你的路由换一个ip， 可能访问太频繁了，被屏蔽了。

**Comment by jones2000** [comment]
不会恢复了， 原来合作的公司，今年开始不搞了， 所以不再提供hqchart后台测试数据和域名了。基础的数据对接可以看例子 [https://github.com/jones2000/HQChart-Super](https://github.com/jones2000/HQChart-Super)

**Comment by jones2000** [comment]
测试数据已全部换成本地数据，不在提供互联网测试数据，本地测试数据具体看 https://github.com/jones2000/HQChart/blob/master/webhqchart.demo/jscommon/umychart.NetworkFilterTest.js
