### ISSUE TITLE
分时图如何标点

### ISSUE THREAD

**Issue by martinljq** [jones2000/HQChart#144]
大大有一个问题，就是使用分时图，怎么对买入的点进行标注，比如买涨的时候是红点，买跌的时候是绿点，然后又如何定时清除这些点

**Comment by jones2000** [comment]
[HQChart使用教程29-走势图如何对接第3方数据4-异动提示信息](https://blog.csdn.net/jones2000/article/details/100516071)

**Comment by martinljq** [comment]
> [HQChart使用教程29-走势图如何对接第3方数据4-异动提示信息](https://blog.csdn.net/jones2000/article/details/100516071)

感谢大大，像一些添加一个图标的我看可以，但是我如果我要加一个图标然后上面有一个倒计时这种是否已有，再麻烦一下大大了

**Comment by martinljq** [comment]
倒计时主要是为了能够让用户看到还有多久清空，然后到了那条线就会清空

**Comment by martinljq** [comment]
大大还有就是x轴某个点，然后一条线高亮

**Comment by jones2000** [comment]
[HQChart实战教程43-K线面积图最后一个数据增加动画点](https://jones2000.blog.csdn.net/article/details/118774299)
