### ISSUE TITLE
订单流测试数据

### ISSUE THREAD

**Issue by quant-ren** [jones2000/HQChart#149]
demo_orderflow 是否可以考虑将 [ 订单流测试数据 ] 抽离到localdata中呢？这样对于一些并不擅长前端的同学可以更友好？

**Comment by jones2000** [comment]
数据是随机生成的, F12自己看代码， 整个例子也就400多行代码。
`
this.CreateTestOrderFlowData=function(hqchartData)  //生成订单流测试数据
`

**Comment by zoutao98** [comment]
订单流的demo代码怎么不见了
