### ISSUE TITLE
滚动条,部分区域黑色

### ISSUE THREAD

**Issue by Lsgo** [jones2000/HQChart#151]
我根据案例设置了滚动条.但是部分区域是黑色的.能帮我看一下是什么原因吗.
![图片](https://user-images.githubusercontent.com/8808422/222952909-0cd807df-45bc-4006-a086-a8549dae08c6.png)

访问地址:http://121.5.196.159:9090/demo/index.html

**Comment by jones2000** [comment]
是bug，已修正，更新最新代码 ver 11777

**Comment by Lsgo** [comment]
改了之后是不是有别的缺陷,主图显示不出来,应该是右边的刻度有问题

**Comment by Lsgo** [comment]
感谢已修复
