### ISSUE TITLE
vueVersion为3的时候，k线图无法拖动和缩放

### ISSUE THREAD

**Issue by LiuYuZhang** [jones2000/HQChart#153]
作者您好，我在uni-app中新建项目，然后在插件市场https://ext.dcloud.net.cn/plugin?id=4591#rating 导入插件，将您测试项目中的hqchart2_test/index.vue文件复制到我所建的项目中，vueVersion:3，然后运行，能跑起来，但是无法缩放，和移动,
如果把vueVersion改成2就正常
![a](https://user-images.githubusercontent.com/16681220/230844884-3ecebc95-aa92-404e-b1b1-e60d45c1fdd5.png)
![b](https://user-images.githubusercontent.com/16681220/230844898-ec00d641-05ae-47c3-ab1e-ca47c47bde1c.png)

**Comment by LiuYuZhang** [comment]
为了方便您测试，以下是测试demo
[testssss.zip](https://github.com/jones2000/HQChart/files/11188408/testssss.zip)

**Comment by jones2000** [comment]
vue2 和 vue3的touch事件的event.touches结构不一样。 需要你自己外部把vue3的event数据转成vue2的touch事件的event结构

**Comment by jones2000** [comment]
` 
//vue3 event 结构  
{
   .......
    "touches": {
        "0": {
            "x": 200.3883514404297,
            "y": 212.44757080078125
        }
    },
   ......
}

`


`
//vue2  event结构
{

    "touches": [
        {
            "x": 151.12344360351562,
            "identifier": 0,
            "y": 189.7986297607422
        }
    ],
}

`
