### ISSUE TITLE
小程序怎么动态的根据数据设置柱子的颜色样式

### ISSUE THREAD

**Issue by zyf540860996** [jones2000/HQChart#157]
求助，微信小程序里，本地的数据怎么动态设置柱子是空心还是实心，然后动态配置颜色。

**Comment by jones2000** [comment]
K线类型（KLine.DrawType）设置为9， 
 [HQChart使用教程1-如何快速创建一个K线图页面](https://blog.csdn.net/jones2000/article/details/90272733) 

然后在数据对接的地方设置每一根K线颜色配置
 [HQChart使用教程30-K线图如何对接第3方数据2-日K数据](https://blog.csdn.net/jones2000/article/details/100552022) 
[HQChart使用教程30-K线图如何对接第3方数据3-1分钟K数据](https://blog.csdn.net/jones2000/article/details/100557649) 
[HQChart使用教程30-K线图如何对接第3方数据14-轮询增量更新日K数据](https://blog.csdn.net/jones2000/article/details/102518334) 
[HQChart使用教程30-K线图如何对接第3方数据15-轮询增量更新1分钟K线数据](https://blog.csdn.net/jones2000/article/details/102518422)

**Comment by zyf540860996** [comment]
感谢！

**Comment by zyf540860996** [comment]
<img width="1367" alt="1" src="https://github.com/jones2000/HQChart/assets/10524382/b92d398d-ea60-40e9-b54a-edc49baaf164">
上图中设置柱子样式后，只有最新的这条数据生效了，前面的数据都没生效，然后删除最新的数据后，显示正常，请问这是怎么产生的？
<img width="1164" alt="2" src="https://github.com/jones2000/HQChart/assets/10524382/17bf364e-2f8d-4b20-a27b-786774fab432">

**Comment by zyf540860996** [comment]
当 今天的前收盘价 和 昨天收盘价 不相等时，自定义K线样式全都失效 ，比如今天20230530，那么20230530前的所有K线样式都会使用初始化的样式，20230530后的样式还是正常显示为自定义的样式。
比如这样的结构
[日期, 前收盘价, 开盘价, 最高价, 最低价, 收盘价, 成交量, 成交金额]
[
  [20230523, 20.29, 20.5, 20.6, 19.85, 20.28, 421908.55, 856673.705],
  [20230524, 20.28, 20.08, 21.07, 19.83, 20.67, 489759.18, 1009411.113],
  [20230525, 20.67, 21.1, 21.77, 20.79, 21.22, 555283.48, 1172006.173],
  [20230526, 21.22, 21.15, 22.5, 21.06, 22.01, 863442.12, 1893938.128],
  [20230529, 22.01, 23.5, 24.21, 23.5, 24.21, 1913144.62, 4611019.625],
  [20230530, 24.1, 24.17, 25.33, 23.9, 25.15, 1681516.83, 4119053.471],
]

**Comment by zyf540860996** [comment]
屏蔽了 umychart.data.wechat.js 文件中的 if (yClose != this.Data[index].Close) break 判断，目前解决了，但是不知道会不会产生其他的影响

**Comment by jones2000** [comment]
试下最新版本， 复权计算的时候没有把颜色一同复制过去。
