### ISSUE TITLE
设置k线柱子的颜色在某一时刻开始就不生效了

### ISSUE THREAD

**Issue by feiye1995** [jones2000/HQChart#159]
![image](https://github.com/jones2000/HQChart/assets/35330322/a4f5494e-b1ea-463a-aa61-178703f77000)
样式全部都设置为：
![image](https://github.com/jones2000/HQChart/assets/35330322/93e9bf8f-312c-4ed4-bc23-970acc460ca9)

**Comment by feiye1995** [comment]
数据是这样的：
{"msg":"操作成功","code":200,"data":{"fields":["ts_code","trade_date","open","high","low","close","pre_close","change","pct_chg","vol","amount"],"items":[["002757.SZ","20230620",17.28,17.88,17.06,17.3,17.26,0.04,0.2317,308698.61,537455.538],["002757.SZ","20230619",17.02,18.17,17.01,17.26,16.79,0.47,2.7993,346333.57,602130.111],["002757.SZ","20230616",16.6,17.04,16.21,16.79,16.9,-0.11,-0.6509,262683.53,437505.138],["002757.SZ","20230615",16.54,17.5,16.24,16.9,16.61,0.29,1.7459,411502.35,692147.965],["002757.SZ","20230614",17.01,17.78,16.5,16.61,16.69,-0.08,-0.4793,556998.25,953402.558],["002757.SZ","20230613",15.36,16.69,14.95,16.69,15.17,1.52,10.0198,319282.86,505272.888],["002757.SZ","20230612",14.88,15.18,14.68,15.17,14.83,0.34,2.2927,169623.25,253466.91],["002757.SZ","20230609",14.24,14.94,14.14,14.83,14.45,0.38,2.6298,156770.25,229055.222],["002757.SZ","20230608",14.31,14.65,14.05,14.45,14.32,0.13,0.9078,97737.25,140667.086],["002757.SZ","20230607",14.09,14.46,14.09,14.32,14.1,0.22,1.5603,79479.91,113815.001],["002757.SZ","20230606",14.46,14.54,14.05,14.1,14.43,-0.33,-2.2869,96783.41,138288.401],["002757.SZ","20230605",15.1,15.13,14.72,15.03,14.97,0.06,0.4008,91411.75,136662.949],["002757.SZ","20230602",14.9,15.08,14.75,14.97,14.85,0.12,0.8081,96009.75,143292.424],["002757.SZ","20230601",14.75,15.0,14.49,14.85,14.85,0.0,0.0,107071.0,158222.092],["002757.SZ","20230531",14.51,14.85,14.45,14.85,14.48,0.37,2.5552,118472.47,174492.82],["002757.SZ","20230530",14.55,14.56,14.19,14.48,14.51,-0.03,-0.2068,82314.47,117958.567],["002757.SZ","20230529",14.34,14.86,14.28,14.51,14.23,0.28,1.9677,121060.91,176989.432],["002757.SZ","20230526",14.19,14.29,13.95,14.23,14.26,-0.03,-0.2104,59473.76,84291.814],["002757.SZ","20230525",14.14,14.36,13.96,14.26,14.15,0.11,0.7774,57562.0,81520.207],["002757.SZ","20230524",13.98,14.26,13.93,14.15,14.04,0.11,0.7835,45531.75,64443.702],["002757.SZ","20230523",14.4,14.42,14.04,14.04,14.35,-0.31,-2.1603,52968.0,75061.654],["002757.SZ","20230522",14.49,14.53,14.21,14.35,14.49,-0.14,-0.9662,46385.0,66449.6],["002757.SZ","20230519",14.57,14.58,14.35,14.49,14.59,-0.1,-0.6854,51693.13,74673.22],["002757.SZ","20230518",14.21,14.7,14.21,14.59,14.22,0.37,2.602,89363.52,129766.061],["002757.SZ","20230517",14.01,14.32,13.95,14.22,14.09,0.13,0.9226,47736.0,67779.27],["002757.SZ","20230516",14.35,14.4,14.0,14.09,14.36,-0.27,-1.8802,57559.25,81650.369],["002757.SZ","20230515",13.9,14.4,13.85,14.36,14.04,0.32,2.2792,87863.0,124826.4],["002757.SZ","20230512",14.45,14.47,14.04,14.04,14.42,-0.38,-2.6352,62700.75,89031.461],["002757.SZ","20230511",14.26,14.55,14.14,14.42,14.35,0.07,0.4878,77085.0,110883.471],["002757.SZ","20230510",14.38,14.6,14.0,14.35,14.37,-0.02,-0.1392,77496.25,111328.159],["002757.SZ","20230509",15.0,15.0,14.37,14.37,15.08,-0.71,-4.7082,122042.75,178303.007],["002757.SZ","20230508",14.98,15.3,14.8,15.08,14.84,0.24,1.6173,135448.75,204013.614],["002757.SZ","20230505",15.2,15.42,14.73,14.84,14.61,0.23,1.5743,245878.75,369461.487],["002757.SZ","20230504",14.02,14.61,14.01,14.61,13.28,1.33,10.0151,99455.25,143389.872]],"has_more":false}}

**Comment by jones2000** [comment]
app 还是 h5？

**Comment by feiye1995** [comment]
#157

**Comment by jones2000** [comment]
取最新版本试试，我修改了。
