### ISSUE TITLE
请问支持滑动到最左边触发分页下载吗

### ISSUE THREAD

**Issue by Unchanged-Is-Changed** [jones2000/HQChart#161]
如题

**Comment by jones2000** [comment]
支持的
[HQChart使用教程41-分钟K线设置拖拽自动下载历史数据](https://blog.csdn.net/jones2000/article/details/102471720)
[HQChart使用教程43-日K线设置拖拽自动下载历史数据](https://blog.csdn.net/jones2000/article/details/102511317)

**Comment by Unchanged-Is-Changed** [comment]
感谢,回复太快了
