### ISSUE TITLE
添加了一个id=10的自定义周期回调AddPeriodCallback,但是调用ChangePeriod(10)的时候,却执行了NetworkFilter里的分笔数据

### ISSUE THREAD

**Issue by Unchanged-Is-Changed** [jones2000/HQChart#162]

**Comment by Unchanged-Is-Changed** [comment]
ChangePeriod(1)可以执行PeriodCalculate里面的代码,ChangePeriod(10)就不行了

**Comment by jones2000** [comment]
0=日线 1=周线 2=月线 3=年线 9=季线 21=双周 22=半年  [40001-50000)=自定义日线
4=1分钟 5=5分钟 6=15分钟 7=30分钟 8=60分钟 11=120分钟 12=240分钟 [20001-30000)=自定义分钟 
秒周期=[30001-32000)
微秒周期=(50000,60000]
10=分笔
