### ISSUE TITLE
关于使用 websocket 更新数据卡顿的问题

### ISSUE THREAD

**Issue by oringecat** [jones2000/HQChart#164]
我在1分钟k线图中使用http+ws数据来展示图表，如果ws推送的频率很高会导致图表卡顿严重，并且图表在更新数据的时候无法向左拖动和操作，会被强制退到到图表最右侧，请问这种情况 HQChart 是否有相关的设置选项可以优化？

**Comment by jones2000** [comment]
数据更新用 [HQChart使用教程30-K线图如何对接第3方数据3-1分钟K数据](https://blog.csdn.net/jones2000/article/details/100557649)

**Comment by oringecat** [comment]
> 数据更新用 [HQChart使用教程30-K线图如何对接第3方数据3-1分钟K数据](https://blog.csdn.net/jones2000/article/details/100557649)

您可能理解错了，我不是问怎么更新数据，而是 websocket 推送频率很高，1秒内可能会有几十上百次，这样k线柱子可以实时跳动，但是由于ws推送频率很高，会导致图表渲染卡顿，并且无法对图表进行拖动和操作，一拖动就会被重置到图表的最右侧，就是想问这种情况下是否有相关的设置选项可以优化？

**Comment by jones2000** [comment]
没遇到过1秒几百次的场景， 我这边只有1秒在20-30次的更新频率，不卡。1秒几百次的刷新，只能是上配置高的电脑+好的显卡。
