### ISSUE TITLE
小程序中使用canvas 2d出错

### ISSUE THREAD

**Issue by stephenhyy** [jones2000/HQChart#167]
你好，按照教程使用canvas 2d画分时图报错
这是我的代码
const self = this;
        // 查询画布节点
        wx.createSelectorQuery()
          .select('#minutechart')
          .fields({
            node: true,
            size: true,
          })
          .exec((res) => {
            debugger;
            // 创建画布元素，绑定画布节点，大小
            const element = new JSCommon.JSCanvasElement();
            element.ID = 'minutechart';
            // eslint-disable-next-line prefer-destructuring
            element.CanvasNode = res[0];
            element.Height = self.height; // 高度宽度需要手动绑定!! 微信没有元素类
            element.Width = self.minWidth;

            // 创建hqchart实例
            self.oneDayMinuteLine.JSChart = JSCommon.JSChart.Init(element);
            self.oneDayMinuteLine.Option.Symbol = self.Symbol;
            self.oneDayMinuteLine.Option.DayCount = dayCount;
            self.oneDayMinuteLine.JSChart.SetOption(self.oneDayMinuteLine.Option);
          });
这里报错
![image](https://github.com/jones2000/HQChart/assets/10447102/cbf859f9-d9d8-451f-b3ee-88d5b9bc0464)
调试不知道什么原因。

**Comment by jones2000** [comment]
不要用vue3，插件代码好像被vue3改了。

**Comment by jones2000** [comment]
[https://github.com/jones2000/HQChart-Super](https://github.com/jones2000/HQChart-Super)
这个里面有示例
