### ISSUE TITLE
vue下缩放出现问题

### ISSUE THREAD

**Issue by 1996brian** [jones2000/HQChart#168]
![Snipaste_2023-11-15_23-10-47](https://github.com/jones2000/HQChart/assets/49873431/b582e252-0a87-4498-aa39-f58d6b3cd066)

按照https://jones2000.github.io/HQChart/webhqchart.demo/samples/demo_orderflow.html 里面的option配置好以后，最大放大到截图那么大，试了很多配置项都不生效，求解

**Comment by 1996brian** [comment]
![image](https://github.com/jones2000/HQChart/assets/49873431/ef5a0498-5069-47e2-83d4-ca4ff5c5a5b6)
我是这样创建K线图的

**Comment by jones2000** [comment]
[HQChart使用教程57-如何调整K线的柱子缩放大小](https://blog.csdn.net/jones2000/article/details/104817724)
