### ISSUE TITLE
图形在微信开发者工具和手机上表现不一

### ISSUE THREAD

**Issue by stephenhyy** [jones2000/HQChart#171]
你好，这边碰到一个问题
如图 
![image](https://github.com/jones2000/HQChart/assets/10447102/4aedb8b6-7d17-4459-b635-7fd2f7062cc0)
![Screenshot_20231201_163239_com tencent mm](https://github.com/jones2000/HQChart/assets/10447102/fe8b8e58-d9da-4736-a449-c3365ff54975)
第一个图开发工具上正常，picker可以把图形盖住
第二张在手机上图形穿透picker很混乱
请问下这是什么原因导致的，我应该在哪里改，还有指标的颜色相关的我可以在哪里改？

**Comment by jones2000** [comment]
canvas 2d 试试

**Comment by stephenhyy** [comment]
我也想用它，但是我们的选型是vue3,别的都用了，上次说了不支持proxy，难办呀

**Comment by jones2000** [comment]
[https://github.com/jones2000/HQChart-Super/tree/master/hqchart_super_eastmoney_demo_wechat](https://github.com/jones2000/HQChart-Super/tree/master/hqchart_super_eastmoney_demo_wechat)
你试下这个例子把。例子里面的选中股票的地方是一个下来的菜单。

**Comment by stephenhyy** [comment]
不是组件的问题，是微信小程序原生canvas就在最高层级，其它组件加z-index也没有用，解决办法就是出现picker或下拉时隐藏canvas，同时生成图片展示

**Comment by jones2000** [comment]
官方就不支持。

[https://developers.weixin.qq.com/miniprogram/dev/component/native-component.html](https://developers.weixin.qq.com/miniprogram/dev/component/native-component.html)

![image](https://github.com/jones2000/HQChart/assets/31334233/5c896a38-5699-48d7-b579-dd83b2af226e)

**Comment by stephenhyy** [comment]
我现在碰到个新问题，就是每次更新图片时，我选择全部重新绘制，这样在手机上有点难看，特别是其中某些线会变颜色，一会又正常，我也看了增量更新但是不生效，super那里又看不懂，你能不能给点代码？

**Comment by stephenhyy** [comment]
我不是原生的picker，只能说类似哈，我是uniapp编译的

**Comment by jones2000** [comment]
[HQChart使用教程30-K线图如何对接第3方数据14-轮询增量更新日K数据](https://blog.csdn.net/jones2000/article/details/102518334) <br>
 [HQChart使用教程30-K线图如何对接第3方数据15-轮询增量更新1分钟K线数据](https://blog.csdn.net/jones2000/article/details/102518422) <br>


https://github.com/jones2000/HQChart/blob/master/vuehqchart/src/jscommon/umychart.NetworkFilterTest.js
![image](https://github.com/jones2000/HQChart/assets/31334233/3606a29c-16fa-4740-b0e5-d99b5f5e4839)

**Comment by stephenhyy** [comment]
我这个是3秒后通过ws在拉取一下数据

**Comment by stephenhyy** [comment]
我在ws的数据回调了调用recvRealTimeData({data:{code:0,stock:[最新]}})按理说也是增量，但是分时的我找不到相关方法。

**Comment by jones2000** [comment]
分时图图只能更新全天的， 没有增量更新1分钟的。 this.Chart.JSChartContainer.RecvMinuteData

**Comment by stephenhyy** [comment]
那这样，对于5日的话怎么办，数据量太大，前4天的基本不变

**Comment by jones2000** [comment]
多日分时。  全量多日数据请求 -> 当天数据请求 -> 当日数据请求....  多日的只请求1次， 其他的都是当天的全量数据。

**Comment by jones2000** [comment]
没有

**Comment by stephenhyy** [comment]
哦，好的，我一直以为是那个重绘会造成指标走样，你看看这个
![image](https://github.com/jones2000/HQChart/assets/10447102/f1dc931f-04e5-4273-9afd-60be2f274913)
![image](https://github.com/jones2000/HQChart/assets/10447102/5451eef9-4bd6-4863-bef7-4885410cd8ed)
但是增量绘制按理不影响呀，不知道怎么回事

**Comment by jones2000** [comment]
小程序用canvas 2d.

**Comment by stephenhyy** [comment]
我想用2d 可以比较奇葩，同一个页面，我只有当日分时生效 
![image](https://github.com/jones2000/HQChart/assets/10447102/b1a62925-b15b-4782-850f-0f214ff421ef)
这个res有值，其它的都是res为null，也画不出来，页面也不报错，我找了很久也没有找到错误，页面有多个canvas是不是这个原因？

**Comment by stephenhyy** [comment]
大佬，部分代码是这样的，res就是获取不到  <canvas class="5minutechart"  canvas-id="5minutechart" id="5minutechart" type="2d"
          :style="{'height':height+'px','width':width+'px'}"
    @touchstart='minutetouchstart' @touchmove='minutetouchmove' @touchend='minutetouchend'/>
	
	const self = this;
      wx.createSelectorQuery()
        .select('#5minutechart')
        .fields({
          node: true,
          size: true,
        })
        .exec((res) => {
          debugger

**Comment by jones2000** [comment]
[https://github.com/jones2000/HQChart-Super/blob/master/hqchart_super_eastmoney_demo_wechat/pages/EastMoney_Data/index.wxml](https://github.com/jones2000/HQChart-Super/blob/master/hqchart_super_eastmoney_demo_wechat/pages/EastMoney_Data/index.wxml)

对比下示例看看吧。 示例是用了2个画布的。

![image](https://github.com/jones2000/HQChart/assets/31334233/33a1f8eb-0894-4360-9f93-b6799f12f7af)

**Comment by stephenhyy** [comment]
真想抽自己，不能数字开头 5minutechart ，换成字母就好了，我和你给的例子基本差不多

**Comment by stephenhyy** [comment]
大佬，我看了下这个
![image](https://github.com/jones2000/HQChart/assets/10447102/c5fca769-61a8-42c8-8deb-26e855a41206)
设置了也没有触发networkfilter，他的工作原理是什么，这个和我拿到新数据后把保存的老数据拼接一起调用HQcallback有什么区别？

**Comment by jones2000** [comment]
setoption的时候 配置好windows

**Comment by stephenhyy** [comment]
没有明白，setoption的时候 配置好windows，配置几个显示几个，但是我想显示2个，其它的切换，难道只能调用函数？

**Comment by jones2000** [comment]
[HQChart使用教程27- 动态设置K线图指标模板](https://blog.csdn.net/jones2000/article/details/100079989)

**Comment by stephenhyy** [comment]
你好，几天没弄这个 我按教程27  
![image](https://github.com/jones2000/HQChart/assets/10447102/6e69a315-0f1f-4b25-a88e-3e537bae8580)
这样设置bu不生效，我看setOption已经更新，但是画出的图还是5,10,20

**Comment by jones2000** [comment]
加QQ交流群问 719525615
