### ISSUE TITLE
走势图的线，一直在最顶部显示

### ISSUE THREAD

**Issue by zyf540860996** [jones2000/HQChart#173]
走势图的线，一直在最顶部显示，怎么调整到中间区域并且让线的上涨下跌幅度变大点， 数据可能确实才几分钱的差距比如 8.21 8.27

**Comment by jones2000** [comment]
发截图看看

**Comment by jones2000** [comment]
少昨收盘价格 
![image](https://github.com/jones2000/HQChart/assets/31334233/bf63b5e3-4d5c-4ef7-ad2e-4a28fb6ce959)
