### ISSUE TITLE
App端的走势图，不显示均线

### ISSUE THREAD

**Issue by zyf540860996** [jones2000/HQChart#174]
配置如下

this.MinuteOption = {
      Type: '分钟走势图',
      Symbol: this.symbol,
      IsAutoUpate: false, 
      CorssCursorTouchEnd: true, 
      IsFullDraw: true,
      Windows: [],
      MinuteLine: {
        IsDrawAreaPrice: true,
        IsShowAveragePrice: true
      },
      Border: {
        Left: 0,
        Right: 0, //右边间距
        Top: 0,
        Bottom: 20
      },
      Frame: [{ SplitCount: 6 }],
      MinuteTitle: {
        IsShow: true,
        IsShowName: false,
        LineCount: 2
      },
      ExtendChart: [{ Name: 'MinuteTooltip' }]
    }

分时数据格式
{
    "name": "",
    "symbol": "300781.sz",
    "amount": 513946190.24,
    "avprice": 36.29,
    "date": "",
    "high": 36.29,
    "increase": 6.05,
    "low": 33.8,
    "open": 33.98,
    "preClose": 30.24,
    "price": 36.29,
    "risefall": 20.01,
    "time": 959,
    "vol": 144359.58,
    "yclose": 33.98,
    "minute": [
        {
            "amount": 514156672.24,
            "avprice": 36.29,
            "date": "",
            "high": 36.29,
            "increase": 6.05,
            "low": 33.8,
            "open": 33.98,
            "preClose": 30.24,
            "price": 36.29,
            "risefall": 20.01,
            "time": 1000,
            "vol": 144417.58
        }
    ]
}

不知道哪里没有配置成功，对比了 webhqchart.demo/samples/chart_minute_phone.html 文件

**Comment by jones2000** [comment]
样本数据
https://github.com/jones2000/HQChart/blob/master/%E6%95%99%E7%A8%8B/%E6%95%B0%E6%8D%AE%E6%A0%B7%E4%BE%8B/%E5%BD%93%E6%97%A5%E5%88%86%E6%97%B6%E5%9B%BE.json

**Comment by zyf540860996** [comment]
{ code: 0, stock: [{time, date, minute: []}] }

这 stock.time 是昨天的收盘时间么，还有 date是 当前开盘日期还是收盘日期

**Comment by zyf540860996** [comment]
使用样例数据 均线显示了，但是对了数据，字段数据全是一样，并不缺少

**Comment by jones2000** [comment]
> { code: 0, stock: [{time, date, minute: []}] }
> 
> 这 stock.time 是昨天的收盘时间么，还有 date是 当前开盘日期还是收盘日期

当天的日期和最新的行情数据时间
