### ISSUE TITLE
请问下VOL指标能不能自定义柱子颜色

### ISSUE THREAD

**Issue by zyf540860996** [jones2000/HQChart#175]
请问下VOL指标能不能自定义柱子颜色

**Comment by jones2000** [comment]
[HQChart麦语法内置函数帮助文档](https://jones2000.blog.csdn.net/article/details/129125330)

自己写一个通达信指标脚本就可以。
![image](https://github.com/jones2000/HQChart/assets/31334233/cbee2d0f-fcbf-4eb1-b354-6e9b812c1177)
