### ISSUE TITLE
网页端怎么让Y轴的刻度文字显示在内部

### ISSUE THREAD

**Issue by zyf540860996** [jones2000/HQChart#178]
网页端怎么让Y轴的刻度文字显示在内部，按照文档中写的设置不生效
https://blog.csdn.net/jones2000/article/details/103174483?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522170389867016777224472849%2522%252C%2522scm%2522%253A%252220140713.130102334.pc%255Fblog.%2522%257D&request_id=170389867016777224472849&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~blog~first_rank_ecpm_v1~rank_v31_ecpm-1-103174483-null-null.nonecase&utm_term=%E5%AD%90%E6%A1%86%E6%9E%B6%E8%AE%BE%E7%BD%AE&spm=1018.2226.3001.4450

Frame: [
        {
          SplitCount: 3,
          IsShowLeftText: true,
          IsShowRightText: true,
          IsShowIndexTitle: false,
          Custom: [
            { Position:'left', PositionEx: 1 }
          ]
        }
]

还是在图外部左右两侧显示

**Comment by jones2000** [comment]
[HQChart使用教程23-Y轴刻度显示设置](https://blog.csdn.net/jones2000/article/details/98320020)
![image](https://github.com/jones2000/HQChart/assets/31334233/4af5b1e9-e7d3-4371-b0de-2185af6ca23d)
