### ISSUE TITLE
请问下刻度上的文字怎么调整大小

### ISSUE THREAD

**Issue by zyf540860996** [jones2000/HQChart#179]
请问下刻度上的文字怎么调整大小，实在不知道写了

**Comment by jones2000** [comment]
[HQChart使用教程4- 如何自定义K线图颜色风格](https://blog.csdn.net/jones2000/article/details/90286933)

![image](https://github.com/jones2000/HQChart/assets/31334233/7c89f6a8-3549-49bd-9d7f-e17ca3d96768)
