### ISSUE TITLE
vite+vue3项目中更新"hqchart"到最新版本"^1.1.12893"，运行报错

### ISSUE THREAD

**Issue by flbamao** [jones2000/HQChart#182]
vite+vue3项目
原来的版本"hqchart": "^1.1.12463"
更新后版本"hqchart": "^1.1.12893"
报错截图
![报错1](https://github.com/jones2000/HQChart/assets/67471797/51c81631-1ae8-4111-8b89-a8f7352e731c)
![报错2](https://github.com/jones2000/HQChart/assets/67471797/e4ec2e33-9031-46a9-ab02-47535394f68d)

**Comment by jones2000** [comment]
安装 babel-runtime/core-js 试试

**Comment by flbamao** [comment]
> 安装 babel-runtime/core-js 试试

安装这个babel-runtime可以了，谢谢大佬
