### ISSUE TITLE
请问一下有参数可以控制鼠标滚动的时候K线缩放快慢的吗

### ISSUE THREAD

**Issue by flbamao** [jones2000/HQChart#183]
现在demo用鼠标滚轮随便一滚动K线就会变得最大或者最小，有参数可以控制K线缩放变慢吗

**Comment by jones2000** [comment]
[HQChart使用教程57-如何调整K线的柱子缩放大小](https://blog.csdn.net/jones2000/article/details/104817724)  增加数组个数

**Comment by flbamao** [comment]
> [HQChart使用教程57-如何调整K线的柱子缩放大小](https://blog.csdn.net/jones2000/article/details/104817724) 增加数组个数

好的，谢谢
