### ISSUE TITLE
指标的输出显示不出来

### ISSUE THREAD

**Issue by dadacf** [jones2000/HQChart#192]
指标如下：
{ID:"11KDJ", Name:"11KDJ",Description:"11KDJ",
            Args:[{Name:'N',Value:7},{Name:'M',Value:3},{Name:'MUL',Value:175},{Name:'DIV',Value:100}],
            Script:
            'LOWV:=LLV(LOW,N);\n\
            HIGHV:=HHV(HIGH,N);\n\
            RSV:=EMA((CLOSE-LOWV)/(HIGHV-LOWV)*100,M);\n\
            K:EMA(RSV,M),COLOR0098FF,POINTDOT;\n\
            D:MA(K,M),COLOR0098FF;\n\
            \n\
            LOWV2:=LLV(LOW,N*MUL/DIV);\n\
            HIGHV2:=HHV(HIGH,N*MUL/DIV);\n\
            RSV2:=EMA((CLOSE-LOWV2)/(HIGHV2-LOWV2)*100,M*MUL/DIV);\n\
            K2:EMA(RSV2,M*MUL/DIV),COLORB0279C,POINTDOT;\n\
            D2:MA(K2,M*MUL/DIV),COLORB0279C;\n\
            \n\
            LOWV3:=LLV(LOW,N*MUL*MUL/DIV/DIV);\n\
            HIGHV3:=HHV(HIGH,N*MUL*MUL/DIV/DIV);\n\
            RSV3:=EMA((CLOSE-LOWV3)/(HIGHV3-LOWV3)*100,M*MUL*MUL/DIV/DIV);\n\
            K3:EMA(RSV3,M*MUL*MUL/DIV/DIV),COLOR5252FF,POINTDOT;\n\
            D3:MA(K3,M*MUL*MUL/DIV/DIV),COLOR5252FF;\n\
            \n\
            LOWV4:=LLV(LOW,N*MUL*MUL*MUL/DIV/DIV/DIV);\n\
            HIGHV4:=HHV(HIGH,N*MUL*MUL*MUL/DIV/DIV/DIV);\n\
            RSV4:=EMA((CLOSE-LOWV4)/(HIGHV4-LOWV4)*100,M*MUL*MUL*MUL/DIV/DIV/DIV);\n\
            K4:EMA(RSV4,M*MUL*MUL*MUL/DIV/DIV/DIV),COLORFF6229 ,POINTDOT;\n\
            D4:MA(K4,M*MUL*MUL*MUL/DIV/DIV/DIV),COLORFF6229;',
            Modify:true, Change:true, Close:true ,FloatPrecision:3}
通过 HQChart.Chart.JSIndexScript.AddIndex(index);加入，输出的线有K,D K2,D2 K3,D3 K4,D4 其中 K,D,K2,K3,K4可显示，D2,D3,D4无法显示

**Comment by jones2000** [comment]
你贴出来的脚本有问题， 不能执行。
![image](https://github.com/jones2000/HQChart/assets/31334233/7dee0969-ede4-4bfb-8793-3338966b4759)
![image](https://github.com/jones2000/HQChart/assets/31334233/0771c997-2b30-4669-86ed-c1acfa7d8b17)

**Comment by jones2000** [comment]
已修正， 更新插件试试。

13050 MA,EMA,LLV,HHV 单值周期数值使用parseInt转成整形

**Comment by dadacf** [comment]
已更新，测试可以实现了，谢谢
