### ISSUE TITLE
指标涨跌显示红色或绿色，现在根据指标颜色来显示

### ISSUE THREAD

**Issue by dadacf** [jones2000/HQChart#195]
如题，指标涨根据K线涨的颜色，指标跌根据K线跌的颜色
![指标涨跌](https://github.com/jones2000/HQChart/assets/2821270/e2db7f4d-5caa-4575-938f-b0070b09d5b8)

**Comment by jones2000** [comment]
ver  13059 已支持

![image](https://github.com/jones2000/HQChart/assets/31334233/84729a6b-09fd-4117-a63c-b2595cd58286)

**Comment by dadacf** [comment]
谢谢
