### ISSUE TITLE
请教如何自定义数据渲染

### ISSUE THREAD

**Issue by zyf540860996** [jones2000/HQChart#196]
求教，如何自定义主图下面其他图形的数据，

<img width="746" alt="image" src="https://github.com/jones2000/HQChart/assets/10524382/3f2b2473-aa69-443c-98a2-ff2bc269f8de">

**Comment by jones2000** [comment]
[HQChart使用教程49-指标配置项说明](https://blog.csdn.net/jones2000/article/details/102928907)

`Windows: 
     [
         {
             Index:"MA"
         },
         {
             API: 
             {
                 Name:'窗口2自定义指标',
                 Script:null,
                 Args:null, 
                 Url:'http://xxxxxx' 
             },
      
             
         },
         {
              API: 
             {
                 Name:'窗口3自定义指标',
                 Script:null,
                 Args:null, 
                 Url:'http://xxxxx' 
             },
         },
                 
     ], //窗口指标
`

**Comment by linannan7777** [comment]
Url返回的数据格式是什么样的？

**Comment by jones2000** [comment]
url随便写，http/https开头就可以。 在networkfilter能截获的

**Comment by linannan7777** [comment]
我指的是通过url请求返回的数据对象格式应该是什么样子？请问有文章讲解吗？我看到部分源码里面要求code为0，要有outdata和stock对象，具体是怎样的

**Comment by jones2000** [comment]
![image](https://github.com/jones2000/HQChart/assets/31334233/a052a213-ce05-4a5b-92cf-d11c3f01cade)
