### ISSUE TITLE
关于区间k线信息查看

### ISSUE THREAD

**Issue by smallCat2012** [jones2000/HQChart#197]
请问教一下。我想实现以下2个功能
1、显示指定时间范围的k线图，比如2022-01-03 ~ 2022-03-03，最左边第一个k线是2022-01-01，最右边的k线是2022-03-01，其他时间范围的k线不显示
2、在1的基础上。在缩小和放大的时候。左右2侧的图形等天数填充。比如缩小3天，那就显示2022-01-01 ~ 2022-03-01的k线

以上需要设置那些参数或调动那个方法？

**Comment by jones2000** [comment]
[HQChart使用教程5- K线图控件操作函数说明](https://blog.csdn.net/jones2000/article/details/90301000)
![image](https://github.com/jones2000/HQChart/assets/31334233/c1b50d67-6b9a-4cde-b2a0-47121ae9ce06)

**Comment by smallCat2012** [comment]
完美。棒棒哒
