### ISSUE TITLE
自定义指标配置项部分手机兼容问题

### ISSUE THREAD

**Issue by zyf540860996** [jones2000/HQChart#200]
指标配置项：

windows = [{
  Name: '测试',
  Script: '自定义脚本',
  IsShowIndexName: true,
  IsDrawTitleBG: true,
  IsShowNameArrow: true,
  IsShowTitleArrow: false
}]

在ios15的浏览器中 当 IsDrawTitleBG 设置为 true时，自定义指标标题无法显示在标题栏上
ios17中可以正常显示并且接受点击事件

参考文档地址：https://blog.csdn.net/jones2000/article/details/103187576

**Comment by zyf540860996** [comment]
简单的排查了下 webhqchart.demo/jscommon/umychart.js 文件 ，发现第52230行的  this.Canvas.roundRect( ToFixedPoint(rtButton.Left), ToFixedPoint(rtButton.Top), ToFixedRect(rtButton.Width), ToFixedRect(rtButton.Height), [roundRadius]); 可能存在问题。

将这段代码注释后，指标名称和箭头都显示了，并且事件也响应了

**Comment by jones2000** [comment]
![image](https://github.com/jones2000/HQChart/assets/31334233/e692e59b-7c28-4421-9ecf-bae996c7eaac)
用最新版本，使用直角试试。
