### ISSUE TITLE
关于美股的盘前盘中盘后数据切换问题

### ISSUE THREAD

**Issue by flbamao** [jones2000/HQChart#204]
请问一下，hqchart支持类似富途牛牛的这种美股的盘前盘中盘后的数据切换吗

https://github.com/jones2000/HQChart/assets/67471797/d3efd053-7170-4a7b-93dd-8834df3df78a

**Comment by jones2000** [comment]
[HQChart实战教程6-自定义分时图](https://blog.csdn.net/jones2000/article/details/104165374)
定义3个类型
XX_盘前.ET
XX_盘中.ET
XX_盘后.ET

**Comment by flbamao** [comment]
> [HQChart实战教程6-自定义分时图](https://blog.csdn.net/jones2000/article/details/104165374) 定义3个类型 XX_盘前.ET XX_盘中.ET XX_盘后.ET

请问NetworkFilter回调里面这个MinuteChartContainer::RequestMinuteData是什么情况下触发的，一直没走到这里面

**Comment by jones2000** [comment]
setoption里面设置了Symbol 就会触发

**Comment by flbamao** [comment]
> setoption里面设置了Symbol 就会触发

最新版的hqchart用demo里面测试数据，会出价格NaN的情况，其他数据正常
![image](https://github.com/jones2000/HQChart/assets/67471797/c432862b-bab2-4a61-b6ae-f6c66c49e43d)

**Comment by jones2000** [comment]
我试了示例是好的，显示正确的。 https://jones2000.github.io/HQChart/webhqchart.demo/demo/et_minute.html

**Comment by flbamao** [comment]
> 我试了示例是好的，显示正确的。 https://jones2000.github.io/HQChart/webhqchart.demo/demo/et_minute.html

我用这个示例也是好的，但是同样的数据换到vue3安装最新的hqchart就不行了。

**Comment by jones2000** [comment]
看不出来，可能是获取小数位数有问题吧。 具体要调试才知道了。
![image](https://github.com/jones2000/HQChart/assets/31334233/2912c37f-a469-498e-83a3-2c2edccefaa4)

**Comment by flbamao** [comment]
> 看不出来，可能是获取小数位数有问题吧。 具体要调试才知道了。 ![image](https://private-user-images.githubusercontent.com/31334233/331958055-2912c37f-a469-498e-83a3-2c2edccefaa4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxODQ4NzEsIm5iZiI6MTcxNjE4NDU3MSwicGF0aCI6Ii8zMTMzNDIzMy8zMzE5NTgwNTUtMjkxMmMzN2YtYTQ2OS00OThlLTgzYTMtMmMyZWRjY2VmYWE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA1NTYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkOGFmOGNhYTY5NGFiYmUxNmE5MmQyOGY3YjgwNmJkYTFkMDAyNmQ1MWVlMzU3MGFiMDI0ZjBjYjUyZjczMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B1Dq8g_vznACL5EEdHyaFxG-_tfkg7vtUla6bg0QEXI)

好的，我调一下看看，谢谢
