### ISSUE TITLE
K线提示信息，里面的数据修改

### ISSUE THREAD

**Issue by coderY7** [jones2000/HQChart#205]
![屏幕截图 2024-06-06 140946](https://github.com/jones2000/HQChart/assets/61097053/092afe99-7daa-47fa-8f82-59f95c1c6b59)
没有返回的数据就不显示

**Comment by jones2000** [comment]
[HQChart使用教程55- 自定义PC端K线图Tooltip](https://blog.csdn.net/jones2000/article/details/104443471)
