### ISSUE TITLE
订单流图表，HBar 的宽度无法正确显示

### ISSUE THREAD

**Issue by playniuniu** [jones2000/HQChart#209]
返回的数据宽度为 13

```json
[
    {
        "Price": 7163,
        "Ask": {
            "Value": 110
        },
        "Bid": {
            "Value": 139
        },
        "HBar": {
            "Color": "rgb(176, 212, 184)",
            "Width": 13,
            "Height": -3,
            "Type": 2
        }
    }
]
```

实际显示的宽度只有 1 个

<img width="737" alt="截屏2024-08-12 22 21 39" src="https://github.com/user-attachments/assets/36105ef5-8d67-4a4b-8777-05839ffeffe5">

完整数据如下

[demo.json](https://github.com/user-attachments/files/16588187/demo.json)

**Comment by jones2000** [comment]
Type应该使用0，其他1和2是带条件的。

"HBar": {
            "Color": "rgb(176, 212, 184)",
            "Width": 13,
            "Height": -3,
            "Type":0 ,
        }

**Comment by playniuniu** [comment]
非常感谢，确实是这样的。

请问一下哪里可以看到不同 Type 对应情况的文档？
