### ISSUE TITLE
http+ws更新K线， 日K、周K 、月K、年K，必须字段是哪些

### ISSUE THREAD

**Issue by linxigirl** [jones2000/HQChart#211]
历史数据代表哪些字段
![aa7b97047e70e59f7034bcde4de7185](https://github.com/user-attachments/assets/d1c32a6f-1600-453a-9add-01ddcee85f08)
ws的数据代表哪些字段，price是最新价，yclose是昨收价，time可以没有吗？
![911cbdc61ad87d8446dbc70749d32ce](https://github.com/user-attachments/assets/9416e192-3383-4c2b-9f5d-9ad59d34b11b)

**Comment by jones2000** [comment]
[HQChart使用教程30-K线图如何对接第3方数据14-轮询增量更新日K数据](https://blog.csdn.net/jones2000/article/details/102518334)
