### ISSUE TITLE
MA指标标题，再移动端显示，如何换行

### ISSUE THREAD

**Issue by huliyou** [jones2000/HQChart#23]
![image](https://user-images.githubusercontent.com/3860373/70195442-a6ae2d80-1740-11ea-8d8d-0cfddaf732c8.png)
如图，在移动端显示，指标标题过长，无法换行显示。

**Comment by huliyou** [comment]
就是添加了多个指标，移动端显示不下。
能否控制指标的显示。

**Comment by jones2000** [comment]
目前只支持单行显示， 不支持多行，
太多了， 只能是2个方案
1 把字体调小
2 把前面的MA()里面的参数不显示了， 这样可以空出来一个宽度。
这2个方案需要我这边你增加配置参数
我==给你加上

**Comment by jones2000** [comment]
代码提交了
`
var option=
{
    Type:'历史K线图',
     .......       
                    
      Windows: 
       [
        {
                  Index: 'MA',
                  IsShortTitle:true,                 //不显示指标参数
                  TitleFont:"8px 微软雅黑",  //自定义标题字体
        }
.......
`
