### ISSUE TITLE
k线最左边时间显示的问题

### ISSUE THREAD

**Issue by liuyangkissu** [jones2000/HQChart#25]
![image](https://user-images.githubusercontent.com/26295632/70226548-fe25bb00-178b-11ea-9ee8-8d595f2a88a4.png)
您好，k线滑到最左边，最早的一个时间点永远是2015年，这明显不对，请您抽时间看一下

**Comment by jones2000** [comment]
我本地无法重现，你有这个页面的外网地址吗？ 我调式下看看
