### ISSUE TITLE
HOW TO SET KLINE DATA, UPDATE KLINE DATA?

### ISSUE THREAD

**Issue by huuhait** [jones2000/HQChart#3]

**Comment by jones2000** [comment]
HQChart使用教程30-K线图如何对接第3方数据1
https://blog.csdn.net/jones2000/article/details/100181279

HQChart使用教程26- K线图及走势图数据自动更新设置
https://blog.csdn.net/jones2000/article/details/99483328

**Comment by jones2000** [comment]
你可以加群， 群里有人在换第3方行情接口

**Comment by huuhait** [comment]
tks
