### ISSUE TITLE
是否可以支持标注开平点在k线图上 

### ISSUE THREAD

**Issue by somewheve** [jones2000/HQChart#33]
！！！大佬 看看呗

**Comment by yutiansut** [comment]
可以的啊..... 你有毒吧

**Comment by Faithforus** [comment]
来凑热闹

**Comment by jones2000** [comment]
标注文字可以看这个教程
 [HQChart使用教程30-K线图如何对接第3方数据12-如何在指标中绘制文字](https://blog.csdn.net/jones2000/article/details/101864046)

你要自己找到K线上平开日期， 把日期和标注的位置传给hqchart。
