### ISSUE TITLE
请问是否支付websocket？

### ISSUE THREAD

**Issue by DemoHu** [jones2000/HQChart#5]
请问是否支付websocket？

websocket接收数据有示例吗？

**Comment by jones2000** [comment]
支持websocket增量更新， 全量下载还是使用api。
HQChart使用教程30-K线图如何对接第3方数据13-使用websocket更新最新K线数据
https://blog.csdn.net/jones2000/article/details/102138784

由于我这边没有websocket源， 所有没测试过， 你可以试下。 有问题可以群里问我

**Comment by jones2000** [comment]
HQChart使用教程29-走势图如何对接第3方数据6-websocket分钟数据
https://blog.csdn.net/jones2000/article/details/102568258
