### ISSUE TITLE
页面拉伸时是否可以支持显示K线数据量的增减，而不是数据宽度

### ISSUE THREAD

**Issue by thinkchl** [jones2000/HQChart#53]

**Comment by jones2000** [comment]
有参考的页面吗？ 没太明白“K线数据量的增减”是怎么样的效果

**Comment by thinkchl** [comment]
tradingview就是这样，现在这个库上指定pagesize，不管页面怎么拉伸，数据量不变，在超宽屏上就出现蜡烛很宽，个人感觉不太好看发自我的华为手机-------- 原始邮件 --------发件人： jones <notifications@github.com>日期： 2020年7月18日周六 下午4:46收件人： jones2000/HQChart <HQChart@noreply.github.com>抄送： thinkchl <think_chl@163.com>, Author <author@noreply.github.com>主    题： Re: [jones2000/HQChart] 页面拉伸时是否可以支持显示K线数据量的增减，而不是数据宽度 (#53)

有参考的页面吗？ 没太明白“K线数据量的增减”是怎么样的效果

**Comment by jones2000** [comment]
鼠标上下滚动轴，或键盘上下键都可以缩放K线的宽度。 手机上两手往外或往内可以缩放K线宽度

**Comment by thinkchl** [comment]
这个我知道，领导是希望电脑端浏览器窗口从小窗口全屏后不改变K线宽度，而是根据窗口大小自动重新计算pagesize发自我的华为手机-------- 原始邮件 --------发件人： jones <notifications@github.com>日期： 2020年7月18日周六 晚上8:40收件人： jones2000/HQChart <HQChart@noreply.github.com>抄送： thinkchl <think_chl@163.com>, Author <author@noreply.github.com>主    题： Re: [jones2000/HQChart] 页面拉伸时是否可以支持显示K线数据量的增减，而不是数据宽度 (#53)

鼠标上下滚动轴，或键盘上下键都可以缩放K线的宽度。 手机上两手往外或往内可以缩放K线宽度

**Comment by jones2000** [comment]
加上了
OnSize({Type:1}) 1=画布大小变化的时候， 不改变K线宽度，根据当前K宽度调整显示个数

**Comment by thinkchl** [comment]
感谢感谢😀发自我的华为手机-------- 原始邮件 --------发件人： jones <notifications@github.com>日期： 2020年7月20日周一 中午12:48收件人： jones2000/HQChart <HQChart@noreply.github.com>抄送： thinkchl <think_chl@163.com>, Author <author@noreply.github.com>主    题： Re: [jones2000/HQChart] 页面拉伸时是否可以支持显示K线数据量的增减，而不是数据宽度 (#53)

加上了

OnSize({Type:1}) 1=画布大小变化的时候， 不改变K线宽度，根据当前K宽度调整显示个数

**Comment by thinkchl** [comment]
从全屏变为小屏显示时，当总数据量小于重新计算的pagesize时，K线显示空白，这时需要往右滑动才能看到数据
