### ISSUE TITLE
请问可以在k线上加入自己的指标吗？

### ISSUE THREAD

**Issue by christan-duplicate** [jones2000/HQChart#6]
比如在某个点加入个箭头或图标之类的？

**Comment by jones2000** [comment]
可以通过做成指标在k线上绘制图标

**Comment by zhaojintao** [comment]
同问，类似缠论笔之类的画线应该如何加呢？

**Comment by jones2000** [comment]
[HQChart使用教程30-K线图如何对接第3方数据11-如何绘制多组自定义图标](https://blog.csdn.net/jones2000/article/details/101757384)
[HQChart使用教程30-K线图如何对接第3方数据12-如何在指标中绘制文字](https://blog.csdn.net/jones2000/article/details/101864046)
[HQChart使用教程30-K线图如何对接第3方数据10-如何绘制自定义线段或多边行指标数据](https://blog.csdn.net/jones2000/article/details/101694618)
