### ISSUE TITLE
C++指标计算引擎有计划封装一个golang版本吗?

### ISSUE THREAD

**Issue by tiansin** [jones2000/HQChart#73]
RT

**Comment by jones2000** [comment]
golang我不会， 目前可以提供 c++ dll， 不知道golang能不能调用c++dll

**Comment by tiansin** [comment]
@jones2000 可以调用,不过还需要提供头文件才行.

**Comment by jones2000** [comment]
[https://github.com/jones2000/hqchartPy2/tree/master/HQChart.CSharp.Free](https://github.com/jones2000/hqchartPy2/tree/master/HQChart.CSharp.Free)
这个是dll的项目， 提供的接口外部调用，

**Comment by tiansin** [comment]
@jones2000 大佬把指标引擎开源了?

**Comment by jones2000** [comment]
社区版本已开源 [https://github.com/jones2000/hqchartPy2/tree/master/HQChartPy2.Free](https://github.com/jones2000/hqchartPy2/tree/master/HQChartPy2.Free)
